sudo: required
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
services:
  - docker
install: 
  - pip install -r requirements.txt
before_script:
  - pip install python-coveralls
script: 
  - make test
after_success:
  - coveralls
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" ==  "false" ]; then
      docker build --tag "$DOCKER_USERNAME"/dagda:0.7.0 .;
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push "$DOCKER_USERNAME"/dagda:0.7.0;
    fi
notifications:
  webhooks: https://app.fossa.io/hooks/travisci